default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  username: <%= ENV.fetch('DB_ENV_POSTGRES_USER')  %>
  password: <%= ENV.fetch('DB_ENV_POSTGRES_PASSWORD') %>
  host: db

development:
  <<: *default
  database: myproject__dev

test:
  <<: *default
  database: myproject__test

production:
  <<: *default
  database: myproject__pro
